# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for quest

  target 'questTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'questUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
